name: my_home_app
description: "Search and sale of real estate app."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Environment
  flutter_dotenv: ^5.1.0

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # Http Client
  dio: ^5.4.3

  #BLoC
  flutter_bloc: ^8.1.6
  bloc_concurrency: ^0.2.5

  # Service Locator
  get_it: ^7.7.0
  injectable: ^2.4.2

  # Logging
  l: ^4.0.2
  stack_trace: ^1.11.1

  # Local storages
  shared_preferences: ^2.2.3

  # Network connection status
  connectivity_plus: ^5.0.2

  # Code-generation
  retrofit: ^4.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generation
  build_runner: ^2.4.11
  freezed: ^2.5.2
  retrofit_generator: ^8.1.0
  json_serializable: ^6.8.0
  flutter_gen_runner: ^5.5.0+1
  injectable_generator: ^2.6.1

  # Lint rules
  surf_lint_rules: ^3.1.0

flutter:
  uses-material-design: true

  assets:
    - .env
