name: my_home_app
description: 'Search and sale of real estate app.'
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Environment
  flutter_dotenv: ^5.2.1

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: any

  # Http Client
  dio: ^5.7.0

  #BLoC
  flutter_bloc: ^9.0.0
  bloc_concurrency: ^0.3.0

  # Service Locator
  get_it: ^8.0.3
  injectable: ^2.5.0

  # Logging
  l: ^4.0.2
  stack_trace: ^1.11.1

  # Local storages
  shared_preferences: ^2.3.5

  # Network connection status
  connectivity_plus: ^6.1.1

  # Navigation
  go_router: ^14.6.3

  # Code-generation
  retrofit: ^4.4.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # Splash
  flutter_native_splash: ^2.4.4

  # Widgets
  flutter_svg: ^2.0.17
  another_xlider: ^3.0.2
  modal_bottom_sheet: ^3.0.0
  flutter_animate: ^4.5.2
  nested: ^1.0.0
  cached_network_image: ^3.4.1
  photo_view: ^0.15.0
  styled_text: ^8.1.0

  # Util & helpers
  url_launcher: ^6.3.1
  share_plus: ^10.1.3
  maps_launcher: ^3.0.0
  clipboard: ^0.1.3
  package_info_plus: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generation
  build_runner: ^2.4.14
  freezed: ^2.5.7
  retrofit_generator: ^9.1.7
  json_serializable: ^6.8.0
  flutter_gen_runner: ^5.8.0
  injectable_generator: ^2.6.2

  flutter_launcher_icons: ^0.14.2

  # Lint rules
  surf_lint_rules: ^3.1.0

flutter_gen:
  output: lib/core/resources/
  line_length: 120

  # Optional
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
    - assets/icons/
    - assets/icons/flags/
    - assets/nav_bar/
    - assets/images/

  fonts:
    - family: TBCXBold
      fonts:
        - asset: fonts/TBCX/TBCX-Bold.ttf
    - family: TBCXMedium
      fonts:
        - asset: fonts/TBCX/TBCX-Medium.ttf
    - family: TBCXRegular
      fonts:
        - asset: fonts/TBCX/TBCX-Regular.ttf
